version: '3'
services:
  app:
    container_name: seabattle
    image: atnyehin/seabattle
    ports:
      - 80:3000
    restart: on-failure
    depends_on:
      - mongo 
  mongo:
    container_name: mongodatabase
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata:
